env:
  global:
  - secure: hVCH3Q5JUNvQhHpjw1VHyu9+SFr2hrKp7PGSCeLaphdA7G6U4S8oNITGkWFsnde+u4Q96DX7jDI8mszFwzadoz9e5XRqF5EcYp30Xh0tL2f0uZc6H4pEoi+FxGjN9cDdHSkutlWwOx85+8v0MaCZGoCjwRO3pfFthFhWyhGx4ULBCex9VF/iuqo9a9RGnNeB05u67Ehf8jDfKwQyKx1e/MsdhQutDPvsdASPiBMXhZGg6hJkXQhxKLfCvPt50bY05KqVu3WNJy1v1hzBnzKIQj8ezPlaKmbf1cR/SPnWNap3jN/cwhl7ls0DtLyOnj5neonLv81heNxLUp8PADFR9eSg33JzVk/GRKfq6RS4It3Hw2VR2INkXSaoL4OqWqrXwnJPRQ7z2cCk3FoziEhesMSMRlDYe7KhfFvrl6+ZndUfIImhLQSyKWAGb+3eEB79G1F1gCvq8Dg6UPSJ8dSaSvHBJuRrKRCGNBVTFESB5tMO1XcDSCOIt6HoDhrhyhZ0ox40rgSKrydW+due+qP8kHK3YA13FUpiKH5nWGlaoopqBYM714gxW7x+kLrkZKS+sJzd3siDEwco4eE8L4nQJtOzW9vnHrP0pjqDNKQ2s1ucjiFuaOEKNg+f1lxKJRdYzjJVNWnDoC3UD0U7YaVzDJeiDgjMNl3Uf4JTZBX33FY=
install:
- easy_install -U setuptools
- pip install -U pip wheel
- pip install sphinx
- pip install sphinx-rtd-theme
- pip install ghp-import
language: python
python: 3.5
script:
- echo "Running script"
- cd docs
- make html
- git config user.name "Travis-CI"
- git config user.email "noreply@travis-ci.org"
- ghp-import -n -m "Generate Sphinx Documentation"  _build/html
- git push -f -q https://$GITHUB_API_KEY@github.com/kdheepak/zip gh-pages
notifications:
  email: false
branches:
  only:
  - master
before_install:
- sudo apt-get -y install jq
- wget `curl https://api.github.com/repos/jgm/pandoc/releases/latest | jq -r '.assets[]
  | .browser_download_url | select(endswith("deb"))'` -O pandoc.deb
- sudo dpkg -i pandoc.deb
before_script:
- git config user.name "Travis-CI"
- git config user.email "noreply@travis-ci.org"
- export PATH=$PATH:/home/travis/.cabal/bin
cache:
  directories:
  - $HOME/.cache/pip
